name: Test_Contract

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test_contract:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: install
        run: |
          npm install

      - name: ci clean
        env:
          HARDHAT_ARBITRUM_URL: ${{ secrets.HARDHAT_ARBITRUM_URL }}
          HARDHAT_ARBITRUM_ACCOUNT_PRIVATE_KEY: ${{ secrets.HARDHAT_ARBITRUM_ACCOUNT_PRIVATE_KEY }}
        run: |
          npm ci
          npx hardhat test